travis:
  secure:
    BINSTAR_TOKEN: LASZSr2N5FyOgb+f+1b1Zjuomfh4xn3BaKcPxC48CysH5VuGVhDB6/x2kgzFzRSQ+aFl8KKSJUqBEonrnTDtFPxNZnKg0kKVJW/26J1O+FEycrXwIo1RkZsxa8M5KMU6hJLW65Nr18ucdr86xBNJV8iCJRnWnfMPkvFDGlww/ssORDIay731zEMDI6Fq7tzSa6Z23qQ+Yq9qrtXLNZoP/w1m9+trVIyH8Ev08FSSbgEHvMi/0F1c03WuTP+A10aXf852FPl0NZ2mJlIC6GzMH6DKxtR9nNp3/qh5G1oRdV7dHayMV8q5oRmsEG+TfFCghpfC/u0XIygGWCE6SDR0rUH4VZOlRrkqfyOOxSgWyAX2i70F3nWeZP0kAK9BHdMLsJxaFwltMh+WAfESmRruS/n+qZigsNfrEcAYD25Xki2BsloqLvINYfwl3Q+KrKO3p6oNDTWGyxXvb095W7E770yfLmOXkG+xilhG/OXgU1YSJV1tqzIb890e9F6+30tRr1C6Dt8+5jo2k4r9i0lJSr89QfXNL58UjpWCvnBZ7K0FxtTvO0CSE7mnY/fLoQYw0P1LgxY7729dgNuqAZ41aq3aw+mjRuI7+eeRBc4JCkcUh6bhmiLXegk/KcUAZp9E79JMq7IXLcFThatwPlcQCiyCSZLkpLiz6BEJ6AjFF1k=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
