travis:
  secure:
    BINSTAR_TOKEN: H13WydlRpXbY+XIat/Eo9UOwDGJ9hUU0TMsn6+67JAlMyuJDVSFTjc4EkpdeYd3rVYyH+rR6/3GopAaNmqv/U30Ap+v/Cf5ihyIB+cR0MD4ZsIhJ4oYEMNYUkpMSIQaZc233TFC0wlJPS8GlUBzawlBYXTRdIoeSvdpOt5vIy3I0TEfJTg6JSCCCcH63wr4TGfH0YjGGhkubto0WxlGoE1cuvx7hLhUAOgCLOrHYpTadWKL1nklZLtBhjSooT7dyoxWevcbs/38/tnKhavlpb1/MflW0dpuIaV8yA/Xpr//Badx01/Vvyp3UpMhQ0oWaqY3CES+Eov2SKfpr/TlL72aeMffIxsqjBpJRfxd7FZL1OrXzc+qJHZKCdESv5o3mlwQ5oxSUV0uI30ljmtzH/RQDrY8ZfwT/e1neZ/K8Bp3yD6yy2WqrKYzcmYkmx+e6p+/VwCcWKQ5L2xd6xOgfzhAoiZGYxzt7CEL8oLwNLjNTsqnO6NMF0db7SEK3gN6/04fhCDzaKOAdeGVtL/qeUlI5LA5BNdLYXsBbtPq9LmqhuNfugTuujs3+uEb7H4HI/ZjHnNbAY8Oy2cqSmx2nlDZefR7pckWW3abLPbgZMKUY9DQR2HIGKocDrELg4cNKw8BPjvTlZVuMfqHhKthDijUh25sQBIVWf8E98bw2MRI=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
