travis:
  secure:
    BINSTAR_TOKEN: YF33HA6sPu5/dDSNIocqsUBJudovdU0Px1XGDHeZ3n5IQFBjg4IIBXUb9kdyi0ncoE/UrqN+CNdJtVCfyU2TwQMmWx2bCHn8ZijUCuC58RJwX9O5UStXiQO1pZMd6cRv7MV4eO0W6EcRtEUTOp+Zo8vX19qUIpTktJ5zzxzinPqBBnvz1PJ8v/FV3N5UJqIq80zJtwRT8NQ+/gB94SAlpkOWsOanMHYizARM3TfvebSR2dC/+WwYeQynGVJAnESVxbB4h4a0sF9pnReaP7qOmVmxdG8YaIYZA/lNCpVJA4tZxBbzpEkzQq5d+S2fK0a+lKsVJlzU59JD2qbaFprXxPvjMSSimC5UzDPLFgJUaZaFYjblVPybOxodKobE3qtm89+b6v0sicwb7p5/Wu1vsy2DpGphEbvYtrcD/s+7URYp1o/wTDxi7IyrXHBF+lyioW3gpw6aQZlx9eMt5SnA0LyF75QE5A24J80SHBPLlJjDMsnLcgaApzfL1t+keFFmr4UTKOzXVkZQrRwY0STMRFg1UYnbIKTOA0UlS9zHHo2SdorhX1WOlkqyq3hGyvUJ0CP1swOh/VIdBn6az05LTSJzcE8RFzv6xESWn1llqtZuLfmdfaeFXmkuZKVxQu5Kdp/MGOkAWNBLzevNGxQADdU8/gRNYW7dkeLnUIptGUI=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
