travis:
  secure:
    BINSTAR_TOKEN: wJ60fMJhdgd7lnpsPzQ4cvjB0pLKIymlEqqx7TyfDpceo+s92z51KiUcaKRA1GOPYnPo90TvJ4NIK9VeSdi+Z7v5Vs/LbXfrVWwjLM3Z+CGBT/sNJythVJKW+/R2c+4/UUQ5IB50x1Cea0Crwdabak9hPm4aKPr9jdgGPq5BB/fvPb4G79sF7AKXwkavXNRqiLUTfNUSUhbT+7Y2KJY5WaC+2y/SXUvoGwBGAkSA2K/4PW7TfdNwNMBeZoGM+z8ude87v1k+9+sr37nzid1s7F15zNpsEIxyh7sSHo8wDykbjIn45wBqfKv+a2/Kmt4QZe/xENYhglMsKIBvfL71/I7m5JXrahY25wN6Z3BNApEyCfxnC4yOnATZE3LKTHSwfOYadPhQ4wZ76D5380+8iQt4moqdeI2Xsgkein1NjxH0/+AJw3HxOMOc5qz6kWi0TMJp/S2tuaO/LOJrZPl/ukMqkxkqWznkky6cGR0l820Yc+8IFKtRIVzdjPTPzn9Q2j1n4B/mPHioIuxEqwWV6j+kDL4DFOmDyUw/+p2skzDvFaIXo5Tri9YNxKhOA+7BSzlRnEzRTePTAUSzAz805XukgZUSiuVOdEYBUUHDAhnRhcXx16Rl9xxqOcZnBxfsXmff7k8SUkkheOWO2wDYS8TqrFWlThFQ1pT2khaaR3M=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
